# Site settings
title:          Saibal De
description:    "Personal Website for Saibal De, Graduate Student Research Assistant (GSRA) at University of Michigan, Ann Arbor"
url:            "https://saibalde.github.io"
baseurl:        ""

# Author
author:
  name:         Saibal De
  url:          https://saibalde.github.io
  email:        saibalde@umich.edu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink:      /:year-:month-:day/:title

# Excludes
exclude: [ Gemfile, Gemfile.lock, CNAME ]
